### ISSUE TITLE
Interfere pop up window creations of org-capture 

### ISSUE THREAD

**Issue by owensys** [casouri/nerdtab#1] opened 2018-05-15 16:55 UTC
I like this mode, i try to use it in my gui emacs, when i type M-x org-capture, it will be create a new pop up window, buffer name is *Org Select*.

When i use this mode on terminal emacs, org-capture no pop up new window.

I do not like pop up new window, so how to disable this behaviour?

My test environment：
Windows10，Emacs 25.3.1 (x86_64-w64-mingw32) GUI
Ubuntu16.04，Emacs 24.5.1 (i686-pc-linux-gnu, GTK+ Version 3.18.9) GUI

**Comment by casouri** [comment] 2018-05-15 22:50
I’ll have a look tonight. Nerdtab interfere magit’s Pop up window, too. 

I think the problem is nertab update tab list whenever buffer changes, and when updating it selects nerdtab window, do edit and select back to original window. That process might cause trouble to pop up windows.

I made a workaround so nertab does not update list if the current buffer is in blacklist, and added magit buffer to blacklist. 

Tonight I can try to change the updating strategy so nerdtab do not interfere pop up windows.

So for now you can add org-capture’s pop up window to nerdtab-regex-blacklist and see if that fixes the problem for now.

P.S.: 用英文大家都看得懂

**Comment by owensys** [comment] 2018-05-16 16:48
How to add org-capture's pop up window to nerdtab-regex-blacklist, just buffer name?
I update local nerdtab.el, restart emacs, and try to use
`(add-to-list 'nerdtab-regex-blacklist "*Org Select*")`
but org-capture still pop up new window.

**Comment by owensys** [comment] 2018-05-16 16:54
The other package youdao-dictionary-mode, will pop up new window if use youdao-dictionary-search.

**Comment by casouri** [comment] 2018-05-16 22:51
I pushed the fix a few hours ago. I tried org capture and it worked fine. 

Could you fetch the latest version and see if org capture works?

**Comment by owensys** [comment] 2018-05-17 03:09
Works fine on my work computer windows7, but not normal on my home computer windows10 tonight.
I will try again in the evening today.

**Comment by owensys** [comment] 2018-05-17 14:38
I just try again on my home computer win10 system, still pop up new window.
This is my screen capture.
[https://snag.gy/nI6kmt.jpg](https://snag.gy/nI6kmt.jpg)
Maybe this problem only has on win10.

**Comment by casouri** [comment] 2018-05-18 00:06
Judging by your screen capture, it seems to be a new frame (instead of a window)? Nerdtab doesn't do anything with frames. 

Could you test if Emacs open a new frame without nerdtab on windows 10?

**Comment by owensys** [comment] 2018-05-18 16:42
Use new-frame or C-x 5 2 always pop up a new emacs window on my windows 10 system.

**Comment by casouri** [comment] 2018-05-20 03:08
No I mean if org capture creates a new frame on windows 10. Ideally, it should only open a new window, right?

**Comment by owensys** [comment] 2018-05-20 15:57
If disable nerdtab, org capture always creates a split window on below, i don't know why.

**Comment by casouri** [comment] 2018-05-22 02:53
I’ll see if I can get a windows 10 and test that.

**Comment by owensys** [comment] 2018-06-02 16:19
Maybe this is org capture problem on win10, i do not use emacs on win10 now. forget it.

**Closed as completed** 2018-06-02 16:19 UTC

**Comment by casouri** [comment] 2018-06-03 05:49
Ok, please reopen if you find anything else.
